---
title: "Assignment Module_8"
author: "Nemin Dholakia"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Installing required packages
```{r}
library(lpSolveAPI)
library(Benchmarking)
```

Input and output vectors
```{r}
x <- matrix(c(150,400,320,520,350,320,0.2,0.7,1.2,2.0,1.2,0.7),ncol = 2)
y <- matrix(c(14000,14000,42000,28000,19000,14000,3500,21000,10500,42000,25000,15000),ncol = 2)
colnames(y) <- c("Reimbursed Patient-Days","Privately Paid Patient-Days")
colnames(x) <- c("Staff Hours per Day","Supplies per Day")
x
y
```
FDH Method
```{r}
FDH <- dea(x,y,RTS = "fdh")
FDH
```

```{r}
peers(FDH)
```
```{r}
lambda(FDH)
```
CRS Method
```{r}
CRS <- dea(x,y,RTS = "crs")
CRS
```
```{r}
peers(CRS)
```
```{r}
lambda(CRS)
```
VRS Method
```{r}
VRS <- dea(x,y,RTS = "vrs")
VRS
```
```{r}
peers(VRS)
```
```{r}
lambda(VRS)
```
IRS Method
```{r}
IRS <- dea(x,y,RTS = "irs")
IRS
```
```{r}
peers(IRS)
```
```{r}
lambda(IRS)
```
DRS Method
```{r}
DRS <- dea(x,y,RTS = "drs")
DRS
```
```{r}
peers(DRS)
```
```{r}
lambda(DRS)
```
FRH Method
```{r}
FRH <- dea(x,y,RTS = "add")
FRH
```
```{r}
peers(FRH)
```
```{r}
lambda(FRH)
```
```{r}
Table <- data.frame(FDH=c(1, 1, 1, 1, 1, 1), CRS=c(1, 1, 1, 1, 0.9775, 0.8675), VRS=c(1, 1, 1, 1, 1, 0.8963), IRS=c(1, 1, 1, 1, 1,0.8963), DRS=c(1, 1, 1, 1, 0.9775, 0.8675), FRH=c(1, 1, 1, 1, 1, 1))
Combined <- cbind(x,y, Table)
Combined
```
DMU 1,2,3 & 4 have efficiencies of 1 for all DEA analysis.

DMU 5 has efficiency of 1 for FDH;VRS;IRS;FRH analysis but efficiency of 0.9775 for both CRS and DRS

DMU 6 has efficiency of 1 for FDH and FRH analysis, for CRS and DRS analysis - 0.8675; VRS and IRS 0.8963